MvcProjeKamp/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKamp.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());

        public ActionResult Index()
        {
            var headingvalues = headingManager.Getlist();
            return View(headingvalues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            //kategori dropdownlist için: önce categorymanagerdan nesne üret
            List<SelectListItem> valuecategory = (from value in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = value.CategoryName,
                                                      Value = value.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.categoryvalues = valuecategory;

            //yazar dropdownlist için: önce writermanagerdan nesne üret
            List<SelectListItem> valuewriter = (from val in writerManager.Getlist()
                                                select new SelectListItem
                                                {
                                                    Text = val.WriterName + " " + val.WriterSurname,
                                                    Value = val.WriterId.ToString()
                                                }).ToList();
            ViewBag.writervalues = valuewriter;
            return View();
        }
        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            //ekleme işleminde bugünün kısa tarihini aldım.
            //viewda bunu görünmeyecek. sql'e tabloya bugunun tarihiyle kaydolacak.
            headingManager.HeadingAddBL(p);
            return RedirectToAction("Index");

        }
       
        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            //her baslıgın kategorısı olacak
            List<SelectListItem> valuecategory = (from val in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = val.CategoryName,
                                                      Value = val.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.categoryvalues = valuecategory;
            var HeadingValue = headingManager.GetByID(id);
            return View(HeadingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p) {
            headingManager.HeadingUpdateBL(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.GetByID(id);
            //headingManager.HeadingRemoveBL(headingValue);
            if (headingValue.HeadingStatus == true)
            {
                headingValue.HeadingStatus = false;
                headingManager.HeadingRemoveBL(headingValue);
            }
            else
            {
                headingValue.HeadingStatus = true;
                headingManager.HeadingRemoveBL(headingValue);
            }
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKamp/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading 
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Yeni Başlık Ekle</h2>

@using (Html.BeginForm("AddHeading", "Heading" , FormMethod.Post))
            {
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />

        @Html.Label("Kategori Adı Seçiniz")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categoryvalues, new { @class = "form-control" })
        @*@Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)*@
        <br />
        @Html.Label("Yazar Adı Seçiniz")
        @Html.DropDownListFor(x=>x.WriterId , (List<SelectListItem>)ViewBag.writervalues, new {@class="form-control"})
        @*@Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterId)*@

        <br />
        <button class="btn btn-outline-danger">Başlık Oluştur</button>
    </div>

            }

MvcProjeKamp/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelle</h2>

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık ID")
        @Html.TextBoxFor(x => x.HeadingId, new { @class = "form-control" })
        <br />
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih Gir")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar ıd")
        @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Seç")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categoryvalues, new { @class = "form-control" })
        <br />

        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcProjeKamp/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*her kategorinin ayrı renkte olması için yazıldı:*@
@{ 
    string color = "";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 10%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    @*her kategori farklı renkte olsun diye böyle bir sey yaptık*@ 
                    <tbody>
                        @foreach (var item in Model)
                        {
                            //bu kod blogu cok kalitesiz oldu düzenle
                            if(item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if(item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Dizi")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Eğitim")
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryName == "Dans")
                            {
                                color = "badge badge-light";
                            }
                            if (item.Category.CategoryName == "Sanat")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryName == "Yemek")
                            {
                                color = "badge badge-dark";
                            }
                            <tr>
                                <td>
                                    @{
                                        string durum = "";
                                        string renk = "";
                                        if (item.HeadingStatus == true)
                                        {
                                            durum = "Aktif";
                                            renk = "text-info";
                                        }
                                        else
                                        {
                                            durum = "Pasif";
                                            renk = "text-danger";
                                        }
                                    }
                                    <p class="@renk">@durum</p>
                                </td>

                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @*@item.HeadingDate*@
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))

                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>@item.HeadingStatus</td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    @{
                                        if (item.HeadingStatus == true)
                                        {
                                            <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingId">
                                                <i class="fas fa-trash">
                                                </i>
                                                Pasif Yap
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-warning btn-sm" href="/Heading/DeleteHeading/@item.HeadingId">
                                                <i class="fas fa-trash">
                                                </i>
                                                Aktif Yap
                                            </a>
                                        }
                                    }


                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

<a href="/Heading/AddHeading/" class="btn btn-primary">Yeni Başlık Oluştur</a>