MvcProjeKamp/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKamp.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        //EfCategoryDal: farklı bir bileşene geçtiğimde bu bileşene daha az bağımlı olması için böyle bir şey yaptım.
        // GET: AdminCategory
        public ActionResult Index()
        {
            //listeleme
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult results = categoryvalidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAddBL(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);


                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetById(id); 
            //silecegimiz degerin id'sini GetById ile buluyoruz 
            cm.CategoryRemoveBL(categoryvalue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var values = cm.GetById(id);
            return View(values);
        }

        [HttpPost]
        public ActionResult UpdateCategory(Category ctg)
        {
            cm.CategoryUpdateBL(ctg);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKamp/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h1>kategori ekleme sayfası</h1>

<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(k => k.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br />
        @Html.Label("Açıklama yazınız")
        @Html.TextBoxFor(k => k.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)

        <br />
        <br />
        <button class="btn btn-danger">Kaydet</button>
    </div>
}

MvcProjeKamp/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
 
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ ADI</th>
        <th>KATEGORİ AÇIKLAMA</th>
        @*<th>DURUM</th>*@
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>BAŞLIKLAR</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            @*<td>@item.CategoryStatus</td>*@
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-outline-danger">Sil</a></td>
            <td><a href="/AdminCategory/UpdateCategory/@item.CategoryId" class="btn btn-outline-success">Güncelle</a></td>
            <td><a href="#" class="btn btn-outline-secondary">Başlıklar</a></td>
        </tr>
    }
</table>
<br />

<a href="/AdminCategory/AddCategory/" class="btn btn-outline-info">Yeni Kategori Ekle</a>

MvcProjeKamp/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelle</h2>

@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
        <br />

        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}